language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=development

before_script:
  - psql -c 'create user root with superuser;'
  - psql -c 'create database cities;' -U postgres
  - npm install -g sequelize-cli @babel/core @babel/cli
  - npm run build
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage