language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=dev

before_script:
  - psql -c 'create database cities;' -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - npm run dbcreate
  - npm run dev 
script:
  - npm test
after_success:
  - npm run coverage